register:
    path: /register
    controller: App\Account\User\Infrastructure\Controller\UserRegisterController::create
    methods: POST

login:
    path: /login
    controller: App\Account\User\Infrastructure\Controller\UserLoginController::login
    methods: POST