"register":
    path: /register
    controller: App\Identity\User\Infrastructure\Controller\UserRegisterController::create
    methods:
        - POST

"login":
    path: /login
    controller: App\Identity\User\Infrastructure\Controller\UserLoginController::login
    methods:
        - POST

"password_recovery":
    path: /recovery/email
    controller: App\Identity\User\Infrastructure\Controller\UserPasswordSendRecoveryEmail::create
    methods:
        - POST
