company-create:
    path: /api/company
    controller: App\Account\Company\Infrastructure\Controller\CompanyCreateController::create
    methods: POST

company-find:
    path: /api/company
    controller: App\Account\Company\Infrastructure\Controller\CompanyFindController::find
    methods: GET

company-update:
    path: /api/company
    controller: App\Account\Company\Infrastructure\Controller\CompanyUpdateController::update
    methods: PUT

company-logo-upload:
    path: /api/company/upload
    controller: App\Account\Company\Infrastructure\Controller\CompanyLogoUploadController::upload
    methods: POST
