member-company-search:
    path: /api/member/company
    controller: App\Account\Member\Infrastructure\Controller\MemberCompanySearchController::search
    methods: GET

member-find:
    path: /api/member
    controller: App\Account\Member\Infrastructure\Controller\MemberFindController::find
    methods: GET