order-create:
    path: /api/order
    controller: App\Sale\Order\Infrastructure\Controller\OrderCreateController::create
    methods: POST

order-approved-sales-summary-report:
    path: /api/order/report/approved-sales-summary
    controller: App\Sale\Order\Infrastructure\Controller\OrderApprovedSalesSummaryReportController::report
    methods: GET

order-approved-sales-by-event-report:
    path: /api/order/report/approved-sales-by-event
    controller: App\Sale\Order\Infrastructure\Controller\OrderApprovedSalesByEventReportController::report
    methods: GET

order-approved-sales-evolution-report:
    path: /api/order/report/approved-sales-evolution
    controller: App\Sale\Order\Infrastructure\Controller\OrderApprovedSalesEvolutionReportController::report
    methods: GET

order-paid-count-summary-report:
    path: /api/order/report/paid-count-summary
    controller: App\Sale\Order\Infrastructure\Controller\OrderPaidCountSummaryReportController::report
    methods: GET

order-cancel:
    path: /api/order/{id}
    controller: App\Sale\Order\Infrastructure\Controller\OrderCancelController::cancel
    methods: DELETE
