payment-create:
    path: /api/payment
    controller: App\Sale\Payment\Infrastructure\Controller\PaymentCreateController::create
    methods: POST

payment-confirm:
    path: /api/payment/{id}
    controller: App\Sale\Payment\Infrastructure\Controller\PaymentConfirmController::confirm
    methods: PUT
