ticket-render:
    path: /api/ticket/{id}
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketRenderController::create
    methods: GET

ticket-sold-summary-report:
    path: /api/ticket/report/sold-summary
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketSoldSummaryReportController::report
    methods: GET

ticket-validation-summary-report:
    path: /api/ticket/report/validation-summary
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketValidationSummaryReportController::report
    methods: GET

ticket-find:
    path: /api/ticket/find/{key}
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketFindController::find
    methods: GET

ticket-validate:
    path: /api/ticket/validate/{key}
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketValidateController::validate
    methods: POST

ticket-search:
    path: /api/ticket
    controller: App\Sale\Ticket\Infrastructure\Controller\TicketSearchController::search
    methods: GET
