user-find:
    path: /api/user
    controller: App\Account\User\Infrastructure\Controller\UserFindController::find
    methods: GET

user-password-update:
    path: /api/user/password
    controller: App\Account\User\Infrastructure\Controller\UserPasswordUpdateController::update
    methods: PUT

user-profile-image-upload:
    path: /api/user/upload
    controller: App\Account\User\Infrastructure\Controller\UserProfileImageUploadController::upload
    methods: POST

user-update:
    path: /api/user
    controller: App\Account\User\Infrastructure\Controller\UserUpdateController::update
    methods: PUT

user-company-search:
    path: /api/user/company/search
    controller: App\Account\User\Infrastructure\Controller\UserCompanySearchController::search
    methods: GET

user-company-switch:
    path: /api/user/company
    controller: App\Account\User\Infrastructure\Controller\UserCompanySwitchController::switch
    methods: PUT