"user-find":
    path: /api/user
    controller: App\Identity\User\Infrastructure\Controller\UserFindController::find
    methods:
        - GET

"user-password-update":
    path: /api/user/password
    controller: App\Identity\User\Infrastructure\Controller\UserPasswordUpdateController::update
    methods:
        - PUT

"user-profile-image-upload":
    path: /api/user/upload
    controller: App\Identity\User\Infrastructure\Controller\UserProfileImageUploadController::upload
    methods:
        - POST
