<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260531152844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(25) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(5) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE company (id UUID NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, email VARCHAR(100) NOT NULL, telephone VARCHAR(25) DEFAULT NULL, web_site VARCHAR(100) DEFAULT NULL, country VARCHAR(2) NOT NULL, city VARCHAR(10) NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE day (id UUID NOT NULL, date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5A0299071F7E88B ON day (event_id)');
        $this->addSql('CREATE TABLE discount (id UUID NOT NULL, code VARCHAR(5) NOT NULL, type INT NOT NULL, value DOUBLE PRECISION NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usage_limit INT NOT NULL, usage_count INT NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E1E0B40E71F7E88B ON discount (event_id)');
        $this->addSql('CREATE TABLE event (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, banner_image VARCHAR(255) DEFAULT NULL, location VARCHAR(255) NOT NULL, country VARCHAR(2) NOT NULL, city VARCHAR(10) NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id UUID NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7979B1AD6 ON event (company_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA712469DE2 ON event (category_id)');
        $this->addSql('CREATE TABLE payment (id UUID NOT NULL, amount DOUBLE PRECISION NOT NULL, payment_method INT NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, external_reference VARCHAR(255) DEFAULT NULL, purchase_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840D558FBEB9 ON payment (purchase_id)');
        $this->addSql('CREATE TABLE "purchase" (id UUID NOT NULL, sub_total DOUBLE PRECISION NOT NULL, tax DOUBLE PRECISION NOT NULL, total DOUBLE PRECISION NOT NULL, status INT NOT NULL, payment_method INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attendee_id UUID NOT NULL, discount_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6117D13BBCFD782A ON "purchase" (attendee_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B4C7C611F ON "purchase" (discount_id)');
        $this->addSql('CREATE TABLE review (id UUID NOT NULL, rating INT NOT NULL, comment TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attendee_id UUID NOT NULL, event_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C6BCFD782A ON review (attendee_id)');
        $this->addSql('CREATE INDEX IDX_794381C671F7E88B ON review (event_id)');
        $this->addSql('CREATE TABLE seat (id UUID NOT NULL, code VARCHAR(10) NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, zone_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D5C36669F2C3FAB ON seat (zone_id)');
        $this->addSql('CREATE TABLE ticket (id UUID NOT NULL, qrcode UUID NOT NULL, name VARCHAR(255) NOT NULL, day_date DATE NOT NULL, zone_name VARCHAR(50) NOT NULL, seat_code VARCHAR(10) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_id UUID NOT NULL, zone_id UUID NOT NULL, seat_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_97A0ADA3A4FF23EC ON ticket (qrcode)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3558FBEB9 ON ticket (purchase_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA39F2C3FAB ON ticket (zone_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3C1DAFE35 ON ticket (seat_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, birth_date DATE NOT NULL, country VARCHAR(2) NOT NULL, city VARCHAR(10) NOT NULL, mobile VARCHAR(25) DEFAULT NULL, profile_image VARCHAR(255) DEFAULT NULL, document_type INT NOT NULL, document_number VARCHAR(50) NOT NULL, type INT NOT NULL, status INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE zone (id UUID NOT NULL, name VARCHAR(50) NOT NULL, total_quantity INT NOT NULL, sold_quantity INT NOT NULL, price DOUBLE PRECISION NOT NULL, hierarchy INT NOT NULL, tax_rate DOUBLE PRECISION NOT NULL, currency VARCHAR(3) NOT NULL, numbered_seating BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, day_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0EBC0079C24126 ON zone (day_id)');
        $this->addSql('ALTER TABLE day ADD CONSTRAINT FK_E5A0299071F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discount ADD CONSTRAINT FK_E1E0B40E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA712469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D558FBEB9 FOREIGN KEY (purchase_id) REFERENCES "purchase" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "purchase" ADD CONSTRAINT FK_6117D13BBCFD782A FOREIGN KEY (attendee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "purchase" ADD CONSTRAINT FK_6117D13B4C7C611F FOREIGN KEY (discount_id) REFERENCES discount (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BCFD782A FOREIGN KEY (attendee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C671F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seat ADD CONSTRAINT FK_3D5C36669F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3558FBEB9 FOREIGN KEY (purchase_id) REFERENCES "purchase" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3C1DAFE35 FOREIGN KEY (seat_id) REFERENCES seat (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC0079C24126 FOREIGN KEY (day_id) REFERENCES day (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE day DROP CONSTRAINT FK_E5A0299071F7E88B');
        $this->addSql('ALTER TABLE discount DROP CONSTRAINT FK_E1E0B40E71F7E88B');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7979B1AD6');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA712469DE2');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D558FBEB9');
        $this->addSql('ALTER TABLE "purchase" DROP CONSTRAINT FK_6117D13BBCFD782A');
        $this->addSql('ALTER TABLE "purchase" DROP CONSTRAINT FK_6117D13B4C7C611F');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6BCFD782A');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C671F7E88B');
        $this->addSql('ALTER TABLE seat DROP CONSTRAINT FK_3D5C36669F2C3FAB');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3558FBEB9');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA39F2C3FAB');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3C1DAFE35');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC0079C24126');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE day');
        $this->addSql('DROP TABLE discount');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE "purchase"');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE seat');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE zone');
    }
}
