controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

identity_user:
    resource: ../src/Identity/User/Infrastructure/Controller/
    type: attribute